services:
  web:
    #image: image_name 
    build:
      context: .
    container_name: php
    ports:
      - "8080:8000"
      - "9001:9000"

    depends_on:
      - "database"

    environment:
      DATABASE_URL: mysql://root:root@database/$DB_NAME?charset=utf8mb4
      MAILER_DSN: smtp://maildev:1025
      APP_ENV: dev
    
    #Needed for xdebug config
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ../project_name_dir:/var/www/project_name_dir
      - ./log:/var/log
      - ../project_name_dir/conf.d:/usr/local/etc/php/conf.d
      #- ./config_php:/usr/local/etc/php

  database:
    image: mysql
    ports: [3306]
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - db-mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: "database"
      PMA_PORT: 3306
#      - PMA_ARBITRARY=1
    depends_on:
      - "database"

  maildev:
    image: maildev/maildev
    restart: always
    command: bin/maildev --web 1080 --smtp 1025 --hide-extensions STARTTLS
    environment:
      - TZ=Europe/Paris
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

volumes:
  db-mysql: {}
